version: "3.7"
services:
  redis:
    image: redis:5
    container_name: redis_app
  app:
    build:
      context: .
    env_file:
      - .env-docker
    container_name: fastapi_app
    command: [ "/app/docker/app.sh" ]
    ports:
      - 9991:8000
    depends_on:
      - redis
  bot:
    build:
      context: .
    env_file:
      - .env-docker
    container_name: bot_app
    command: python -m src.bot.bot_main
    depends_on:
      - app
      - redis
  console:
    build:
      context: .
    env_file:
      - .env-docker
    container_name: console
    command: python -m  src.main --file src/test.csv --start_date 2023-10-01 --end_date 2023-10-03
    depends_on:
      - redis
      - app
